Gerdemann:
  PhotoSphere:
    googleApiKey: ENTER_HERE_THE_GOOGLE_API_KEY
Neos:
  Neos:
    userInterface:
      translation:
        autoInclude:
          Gerdemann.PhotoSphere:
            - 'NodeTypes/*'
    fusion:
      autoInclude:
        Gerdemann.PhotoSphere: true
